Finaliser la fonction d'import des thématiques #159
jdev-org/mviewerstudio pull request #29
Opened 2023-04-04 12:31 UTC by Agath21

Modifications réalisées : 
-  Mise à jour de l'interface en affichant le nom, la description, l'organisme
-  Barre de recherche pour filtrer les thématiques
-  Pagination et gestion de l'affichage
-  Filtrer les thématiques et n'afficher que celle avec le statut "à jour"
-  Créer un nouveau paramètre pour la gestion de l'affichage des couches au sein de la thématique layersvisibility
-  Création d'une nouvelle modale pour la gestion des options
-  Documentation

2023-04-11 08:06 UTC, Gaetanbrl commented
@spelhate ==> Une petite revue ?

2023-04-11 08:14 UTC, spelhate requested changes

2023-04-11 08:14 UTC, spelhate commented on lib/mv.js
> +        },
espaces superflus

2023-04-11 08:14 UTC, spelhate commented on css/mviewerstudio.css
> +		font-family: 'Poppins', sans-serif;
Toute la mise en forme du fichier a été modifiée, ce qui rend illisibles les modifications.
Il faut peut-être utiliser le linter proposé par @Gaetanbrl

2023-04-11 08:15 UTC, spelhate commented
> @spelhate ==> Une petite revue ?

Je me suis simplement concentré sur la forme pour la revue ;-)

2023-04-11 13:54 UTC, Gaetanbrl commented on css/mviewerstudio.css
> +		font-family: 'Poppins', sans-serif;
oui depuis le début j'y pense ... y a des patch à appliquer partout dans le code de studio pour tous les formats (css, js, html...) :

https://github.com/mviewer/mviewerstudio/issues/184

Mais si on fait ca, alors la PR sera un tas de modifications sans la possibilité de voir ce qui a changer.

La méthode devra être la même que pour mviewer.

En attendant on peut pas faire grand chose à part faire au mieux quand on touche à des lignes ... :)

2023-04-11 14:04 UTC, Gaetanbrl requested changes
@Agath21 est-ce possible de seulement pousser les modifications du CSS et non pas les modifications de style de code avec ?

C'est pas super évident car aucune indentation ne semblait adéquate vis à vis du linter que tu peux utiliser mais ca permettra de mieux identifier la modifications.

2023-04-11 14:28 UTC, Agath21 commented
Erreur de ma part, je l'ai passé dans un beautifer au passage, navrée ... 
Je reprends le fichier de base et répercute seulement les modifications nécessaires

2023-04-11 15:29 UTC, Gaetanbrl commented
> je reprends le fichier de base et répercute seulement les modifications nécessaires

Super merci ! ;)

2023-04-12 08:57 UTC, Agath21 commented on css/mviewerstudio.css
> +		font-family: 'Poppins', sans-serif;
C'est ok j'ai répercuté seulement mes modifications sur le fichier css de base, encore dsl

2023-04-12 09:04 UTC, Gaetanbrl approved these changes

2023-04-12 09:06 UTC, merged

2023-04-12 09:07 UTC, Gaetanbrl commented
@spelhate @lecault je merge - vous pouvez tester cette PR sur la branche develop-meg